version: 2
workflows:
  version: 2
  sample-nix-workflow:
    jobs:
      - nix/build:
          cache-key: hello-haskell

      - execute-hello:
          requires:
            - build

jobs:
  execute-hello:
    docker:
      - image: circleci/buildpack-deps:18.04-curl-dind
    steps:
      - attach_workspace:
          at: /project/root
      - run:
          command: /project/root/result/bin/hello-haskell
