version: 2
workflows:
  version: 2
  sample-nix-workflow:
    jobs:
      - nix/build:
          cache-key: hello-haskell

      - execute-hello:
          requires:
            - build

jobs:
  execute-hello:
    docker:
      - image: alpine:3.6
    steps:
      - attach_workspace:
          at: /project/root
      - run:
          command: /project/root/result/bin/hello-haskell
