version: 2
workflows:
  version: 2
  sample-nix-workflow:
    jobs:
      - nix/build
      - execute-hello:
          requires:
            - build

jobs:
  execute-hello:
    steps:
      - attach_workspace:
          at: /project/root
      - run:
          command: /project/root/result/bin/hello-haskell
