version: 2
workflows:
  version: 2
  sample-nix-workflow:
    jobs:
    - build: {}
    - execute-hello:
        requires:
        - build
jobs:
  build:
    description: Build a default.nix file
    docker:
    - image: lnl7/nix
    steps:
    - checkout
    - restore_cache:
        keys:
        - hello-haskell-{{ checksum &quot;app.nix&quot; }}-{{ checksum &quot;default.nix&quot; }}
    - run:
        command: nix build
    - save_cache:
        key: hello-haskell-{{ checksum &quot;app.nix&quot; }}-{{ checksum &quot;default.nix&quot; }}
        paths:
        - /nix
    - persist_to_workspace:
        root: /root/project
        paths:
        - result
  execute-hello:
    docker:
    - image: alpine:3.6
    steps:
    - attach_workspace:
        at: /project/root
    - run:
        command: /project/root/result/bin/hello-haskell
