version: 2
workflows:
  version: 2
  sample-nix-workflow:
    jobs:
    - shell: {}
jobs:
  shell:
    description: Run a command in a nix shell
    docker:
    - image: lnl7/nix
    steps:
    - checkout
    - run:
        command: nix-shell --command 'java -version'
