version: 2
workflows:
  version: 2
  sample-nix-workflow:
    jobs:
    - build: {}
jobs:
  build:
    description: Build a default.nix file
    docker:
    - image: lnl7/nix
    steps:
    - checkout
    - restore_cache:
        keys:
        - hello-haskell
    - run:
        command: nix build
    - run:
        command: /root/project/result/bin/hello-haskell
    - save_cache:
        key: hello-haskell
        paths:
        - /nix
    - persist_to_workspace:
        root: /root/project
        paths:
        - result
